export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const PURCHASE_TACO_START = 'PURCHASE_TACO_START';
export const PURCHASE_TACO_SUCCESS = 'PURCHASE_TACO_SUCCESS';
export const PURCHASE_TACO_FAIL = 'PURCHASE_TACO_FAIL';
